name: Build stable magisk for k40g

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build on ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          repository: "topjohnwu/Magisk"
          ref: 'v23.0'
          submodules: 'recursive'
          fetch-depth: 0

      - name: Edit for k40g
        run: |
          sed -i '/# Sign chromeos boot/ i ui_print "- rebuild for k40g酷安@响當當"\n.\/magiskboot hexpatch new-boot.img "0300000000617662746F6F6C20" "0000000000617662746F6F6C20"' ./scripts/boot_patch.sh
          sed -i 's/主页/主页(k40g n10p)/' ./app/src/main/res/values-zh-rCN/strings.xml
          wget -O magisk.jks https://cdn.jsdelivr.net/gh/carey036/modify_magisk_for_k40g/magisk.jks
          sed -i '/keyStore/d' config.prop.sample
          sed -i '/keyStorePass/d' config.prop.sample
          sed -i '/keyPass/d' config.prop.sample
          sed -i '/keyAlias/d' config.prop.sample
          sed -i '/outdir/d' config.prop.sample
          sed -i '/version/d' config.prop.sample
          echo "version="`git log -1 --format='%h'` >> config.prop.sample
          echo "outdir=out" >> config.prop.sample
          echo "keyStore=./magisk.jks" >> config.prop.sample
          echo "keyStorePass=magisk" >> config.prop.sample
          echo "keyAlias=xingsuo" >> config.prop.sample
          echo "keyPass=magisk" >> config.prop.sample
          cat config.prop.sample > config.prop

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up GitHub env (Unix)
        if: runner.os != 'Windows'
        run: |
          ndk_ver=$(sed -n 's/^magisk.fullNdkVersion=//p' gradle.properties)
          echo ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT >> $GITHUB_ENV
          echo MAGISK_NDK_VERSION=$ndk_ver >> $GITHUB_ENV

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache NDK
        id: ndk-cache
        uses: actions/cache@v2
        with:
          path: ${{ env.ANDROID_SDK_ROOT }}/ndk/magisk
          key: ${{ runner.os }}-ndk-${{ env.MAGISK_NDK_VERSION }}

      - name: Set up NDK
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: python build.py ndk

      - name: Build release
        run: |
          python build.py -vr all
          cp -f ./out/app-release.apk /opt/Magisk_stable_app.apk

      - name: Refresh flag
        run: touch gradle.properties
        shell: bash

      # Only upload artifacts built on Linux
      - name: Upload build artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: out

      #upload file to repo
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: upload to repo
        run: |
          cp /opt/Magisk_stable_app.apk ./release/Magisk_stable_app.apk
          git config --global user.name ${{ secrets.GITHUBUSER }}
          git config --global user.email ${{ secrets.GITHUBEMAIL }}
          git add ./release/Magisk_stable_app.apk
          git commit -m 'build stable Magisk' && echo commit
          git push origin main && echo push!